import {initializeApp} from "firebase-admin/app";
import {getAuth} from "firebase-admin/auth";
import {FieldValue, GeoPoint, Timestamp, getFirestore} from "firebase-admin/firestore";
import {getMessaging} from "firebase-admin/messaging";
import {getFunctions} from "firebase-admin/functions";
import {defineSecret} from "firebase-functions/params";
import {HttpsError, onCall, CallableRequest} from "firebase-functions/v2/https";
import {onDocumentCreated, onDocumentWritten} from "firebase-functions/v2/firestore";
import {onTaskDispatched} from "firebase-functions/v2/tasks";
import {geohashForLocation, geohashQueryBounds, distanceBetween} from "geofire-common";

initializeApp();
const db=getFirestore(); const REGION="asia-south1"; const routesKey=defineSecret("GOOGLE_ROUTES_API_KEY");
type Point={lat:number;lng:number;address?:string};
const rideRef=(id:string)=>db.collection("rides").doc(id);
const queueRef=(stand:string,driver:string)=>db.collection("stands").doc(stand).collection("active_queue").doc(driver);

function auth(req:CallableRequest<unknown>,role?:string){if(!req.auth)throw new HttpsError("unauthenticated","Sign in required");if(role&&req.auth.token.role!==role)throw new HttpsError("permission-denied",`${role} account required`);return req.auth.uid}
function text(v:unknown,name:string,max=300){if(typeof v!=="string"||!v.trim()||v.length>max)throw new HttpsError("invalid-argument",`${name} is invalid`);return v.trim()}
function point(v:any,name:string):Point{const lat=Number(v?.lat),lng=Number(v?.lng);if(!Number.isFinite(lat)||!Number.isFinite(lng)||lat < -90||lat > 90||lng < -180||lng > 180)throw new HttpsError("invalid-argument",`${name} coordinates are invalid`);return{lat,lng,address:typeof v.address==="string"?v.address.slice(0,300):""}}
async function roleOf(uid:string){return (await getAuth().getUser(uid)).customClaims?.role}

export const joinStand=onCall({region:REGION},async req=>{const uid=auth(req,"driver");const standId=text((req.data as any)?.standId,"standId",80);const profile=(await db.collection("drivers").doc(uid).get()).data()||{};const now=Timestamp.now();await db.runTransaction(async tx=>{const ref=queueRef(standId,uid),snap=await tx.get(ref);const old=snap.data();const completed=old?.lastTripCompletedAt??null;tx.set(ref,{driverId:uid,name:profile.name??"Driver",vehicleNumber:profile.vehicleNumber??"",phone:profile.phone??"",photoUrl:profile.photoUrl??"",upiId:profile.upiId??"",rating:profile.rating??0,fcmToken:profile.fcmToken??"",isDutyOn:true,isBusy:old?.isBusy===true,joinedStandAt:old?.joinedStandAt??now,lastTripCompletedAt:completed,effectiveQueueTime:completed??old?.joinedStandAt??now,queueTier:completed?1:0,penaltyUntil:old?.penaltyUntil??null,updatedAt:now},{merge:true});tx.set(db.collection("drivers").doc(uid),{isDutyOn:true,standId,updatedAt:now},{merge:true})});return{ok:true}});

export const leaveStand=onCall({region:REGION},async req=>{const uid=auth(req,"driver");const standId=text((req.data as any)?.standId,"standId",80);await db.runTransaction(async tx=>{const q=queueRef(standId,uid),s=await tx.get(q);if(s.data()?.isBusy)throw new HttpsError("failed-precondition","Complete the active ride first");tx.set(q,{isDutyOn:false,offeredRideId:null,updatedAt:Timestamp.now()},{merge:true});tx.set(db.collection("drivers").doc(uid),{isDutyOn:false},{merge:true})});return{ok:true}});

async function routeQuote(pickup:Point,drop:Point){
  const response=await fetch("https://routes.googleapis.com/directions/v2:computeRoutes",{method:"POST",signal:AbortSignal.timeout(8_000),headers:{"Content-Type":"application/json","X-Goog-Api-Key":routesKey.value(),"X-Goog-FieldMask":"routes.distanceMeters,routes.duration,routes.polyline.encodedPolyline"},body:JSON.stringify({origin:{location:{latLng:{latitude:pickup.lat,longitude:pickup.lng}}},destination:{location:{latLng:{latitude:drop.lat,longitude:drop.lng}}},travelMode:"DRIVE",routingPreference:"TRAFFIC_AWARE"})});
  if(!response.ok)throw new HttpsError("unavailable","Route service unavailable");const body:any=await response.json();const route=body.routes?.[0];if(!route)throw new HttpsError("not-found","No drivable route found");const distanceMeters=Number(route.distanceMeters),durationSeconds=parseInt(String(route.duration??"0s"),10);
  const cfg=(await db.doc("config/fare_rules").get()).data()||{};const base=Number(cfg.baseFarePaise??4000),baseMeters=Number(cfg.baseDistanceMeters??1500),perKm=Number(cfg.perKmPaise??1500),minimum=Number(cfg.minimumFarePaise??4000);const farePaise=Math.max(minimum,Math.round(base+Math.max(0,distanceMeters-baseMeters)/1000*perKm));
  return{farePaise,distanceMeters,durationSeconds,encodedPolyline:String(route.polyline?.encodedPolyline??"")};
}
export const quoteRide=onCall({region:REGION,secrets:[routesKey]},async req=>{auth(req,"customer");return routeQuote(point((req.data as any)?.pickup,"pickup"),point((req.data as any)?.drop,"drop"))});

export const createRide=onCall({region:REGION,secrets:[routesKey]},async req=>{const uid=auth(req,"customer");const d:any=req.data;const standId=text(d?.standId,"standId",80),pickup=point(d?.pickup,"pickup"),drop=point(d?.drop,"drop");const quote=await routeQuote(pickup,drop);const ref=db.collection("rides").doc();await ref.create({rideId:ref.id,standId,customerId:uid,driverId:null,offeredDriverId:null,pickup,drop,fare:quote.farePaise,distance:quote.distanceMeters,durationSeconds:quote.durationSeconds,encodedPolyline:quote.encodedPolyline,status:"REQUESTED",offerVersion:0,createdAt:Timestamp.now(),updatedAt:Timestamp.now()});return{rideId:ref.id,...quote}});

type Offer={driverId:string;token:string;version:number;ride:any}|null;
async function enqueueTimeout(rideId:string,version:number,driverId:string|null){await getFunctions().taskQueue(`locations/${REGION}/functions/rideOfferTimeout`).enqueue({rideId,version,driverId},{scheduleDelaySeconds:20})}
async function dispatchNext(rideId:string):Promise<Offer>{
  const result=await db.runTransaction<Offer>(async tx=>{const ref=rideRef(rideId),snap=await tx.get(ref);if(!snap.exists)return null;const ride=snap.data()!;if(ride.status!=="REQUESTED"||ride.offeredDriverId)return null;const q=db.collection("stands").doc(ride.standId).collection("active_queue").where("isDutyOn","==",true).where("isBusy","==",false).orderBy("queueTier").orderBy("effectiveQueueTime").limit(30);const candidates=await tx.get(q);const now=Timestamp.now();const chosen=candidates.docs.find(d=>{const x=d.data();return !x.offeredRideId&&(!x.penaltyUntil||x.penaltyUntil.toMillis()<=now.toMillis())});const version=Number(ride.offerVersion??0)+1;if(!chosen){tx.update(ref,{dispatchState:"NO_DRIVER",updatedAt:now,offerVersion:version});return{driverId:"",token:"",version,ride}}const driver=chosen.data();tx.update(ref,{offeredDriverId:chosen.id,offerVersion:version,offerExpiresAt:Timestamp.fromMillis(now.toMillis()+20_000),dispatchState:"OFFERED",updatedAt:now,offerHistory:FieldValue.arrayUnion({driverId:chosen.id,offeredAt:now,version})});tx.update(chosen.ref,{offeredRideId:rideId,updatedAt:now});return{driverId:chosen.id,token:String(driver.fcmToken??""),version,ride}});
  if(!result)return null;if(!result.driverId){await enqueueTimeout(rideId,result.version,null);return result}if(result.token){await getMessaging().send({token:result.token,data:{type:"RIDE_OFFER",rideId,pickup:String(result.ride.pickup?.address??"Pickup"),drop:String(result.ride.drop?.address??"Drop"),fare:(Number(result.ride.fare??0)/100).toFixed(2),distanceKm:(Number(result.ride.distance??0)/1000).toFixed(1),offerVersion:String(result.version)},android:{priority:"high",ttl:20_000}})}await enqueueTimeout(rideId,result.version,result.driverId);return result;
}

export const dispatchNewRide=onDocumentCreated({document:"rides/{rideId}",region:REGION},async e=>{if(e.data?.data().status==="REQUESTED")await dispatchNext(e.params.rideId)});

export const rideOfferTimeout=onTaskDispatched({region:REGION,retryConfig:{maxAttempts:2,minBackoffSeconds:5},rateLimits:{maxConcurrentDispatches:100}},async req=>{const{rideId,version,driverId}=req.data as any;let cascade=false;await db.runTransaction(async tx=>{const ref=rideRef(rideId),snap=await tx.get(ref);if(!snap.exists)return;const ride=snap.data()!;if(ride.status!=="REQUESTED"||Number(ride.offerVersion)!==Number(version))return;if(driverId&&ride.offeredDriverId!==driverId)return;const now=Timestamp.now();if(driverId){const q=queueRef(ride.standId,driverId);tx.set(q,{offeredRideId:null,penaltyUntil:Timestamp.fromMillis(now.toMillis()+90_000),queueTier:1,effectiveQueueTime:now,declineCount:FieldValue.increment(1),updatedAt:now},{merge:true})}tx.update(ref,{offeredDriverId:null,dispatchState:"RETRYING",updatedAt:now});cascade=true});if(cascade)await dispatchNext(rideId)});

export const acceptRide=onCall({region:REGION},async req=>{const uid=auth(req,"driver"),rideId=text((req.data as any)?.rideId,"rideId",100);await db.runTransaction(async tx=>{const ref=rideRef(rideId),rideSnap=await tx.get(ref);if(!rideSnap.exists)throw new HttpsError("not-found","Ride not found");const ride=rideSnap.data()!;if(ride.status!=="REQUESTED"||ride.offeredDriverId!==uid)throw new HttpsError("failed-precondition","Offer is no longer available");if(ride.offerExpiresAt.toMillis()<Date.now())throw new HttpsError("deadline-exceeded","Offer expired");const q=queueRef(ride.standId,uid),qs=await tx.get(q),driver=qs.data()||{};const snapshot={driverId:uid,name:driver.name??"Driver",vehicleNumber:driver.vehicleNumber??"",phone:driver.phone??"",photoUrl:driver.photoUrl??"",upiId:driver.upiId??"",rating:driver.rating??0};tx.update(ref,{status:"ASSIGNED",driverId:uid,offeredDriverId:null,assignedAt:Timestamp.now(),driverSnapshot:snapshot,updatedAt:Timestamp.now()});tx.set(q,{isBusy:true,offeredRideId:null,activeRideId:rideId,updatedAt:Timestamp.now()},{merge:true});tx.set(db.collection("drivers").doc(uid),{isBusy:true,activeRideId:rideId},{merge:true})});return{ok:true,rideId}});

export const declineRide=onCall({region:REGION},async req=>{const uid=auth(req,"driver"),rideId=text((req.data as any)?.rideId,"rideId",100);let cascade=false;await db.runTransaction(async tx=>{const ref=rideRef(rideId),snap=await tx.get(ref);if(!snap.exists)throw new HttpsError("not-found","Ride not found");const ride=snap.data()!;if(ride.status!=="REQUESTED"||ride.offeredDriverId!==uid)return;const now=Timestamp.now();tx.update(ref,{offeredDriverId:null,dispatchState:"DECLINED",updatedAt:now});tx.set(queueRef(ride.standId,uid),{offeredRideId:null,penaltyUntil:Timestamp.fromMillis(now.toMillis()+90_000),queueTier:1,effectiveQueueTime:now,declineCount:FieldValue.increment(1),updatedAt:now},{merge:true});cascade=true});if(cascade)await dispatchNext(rideId);return{ok:true}});

export const cancelRide=onCall({region:REGION},async req=>{const uid=auth(req,"customer"),rideId=text((req.data as any)?.rideId,"rideId",100);await db.runTransaction(async tx=>{const ref=rideRef(rideId),snap=await tx.get(ref);if(!snap.exists)throw new HttpsError("not-found","Ride not found");const ride=snap.data()!;if(ride.customerId!==uid)throw new HttpsError("permission-denied","Not your ride");if(!["REQUESTED","ASSIGNED","ARRIVED"].includes(ride.status))throw new HttpsError("failed-precondition","Ride can no longer be cancelled");const now=Timestamp.now();tx.update(ref,{status:"CANCELLED",offeredDriverId:null,cancelledAt:now,updatedAt:now});if(ride.offeredDriverId)tx.set(queueRef(ride.standId,ride.offeredDriverId),{offeredRideId:null,updatedAt:now},{merge:true});if(ride.driverId){tx.set(queueRef(ride.standId,ride.driverId),{isBusy:false,activeRideId:null,updatedAt:now},{merge:true});tx.set(db.collection("drivers").doc(ride.driverId),{isBusy:false,activeRideId:null},{merge:true})}});return{ok:true}});

export const transitionRide=onCall({region:REGION},async req=>{const uid=auth(req,"driver"),rideId=text((req.data as any)?.rideId,"rideId",100),action=text((req.data as any)?.action,"action",20);await db.runTransaction(async tx=>{const ref=rideRef(rideId),snap=await tx.get(ref);if(!snap.exists)throw new HttpsError("not-found","Ride not found");const ride=snap.data()!;if(ride.driverId!==uid)throw new HttpsError("permission-denied","Not your ride");const now=Timestamp.now();if(action==="WAITING"){if(!["ARRIVED","ON_TRIP"].includes(ride.status))throw new HttpsError("failed-precondition","Waiting is unavailable now");tx.update(ref,{isWaiting:!ride.isWaiting,waitingChangedAt:now,updatedAt:now});return}const next:any={ARRIVED:["ASSIGNED","ARRIVED"],PICKED:["ARRIVED","ON_TRIP"],DROPPED:["ON_TRIP","COMPLETED"]}[action];if(!next||ride.status!==next[0])throw new HttpsError("failed-precondition",`Cannot ${action} from ${ride.status}`);tx.update(ref,{status:next[1],[`${next[1].toLowerCase()}At`]:now,updatedAt:now});if(next[1]==="COMPLETED"){const q=queueRef(ride.standId,uid);tx.set(q,{isBusy:false,activeRideId:null,lastTripCompletedAt:now,effectiveQueueTime:now,queueTier:1,penaltyUntil:null,updatedAt:now},{merge:true});tx.set(db.collection("drivers").doc(uid),{isBusy:false,activeRideId:null},{merge:true})}});return{ok:true}});

export const nearbyDrivers=onCall({region:REGION},async req=>{auth(req,"customer");const lat=Number((req.data as any)?.lat),lng=Number((req.data as any)?.lng),radiusKm=Math.min(10,Math.max(.2,Number((req.data as any)?.radiusKm??3)));point({lat,lng},"center");const bounds=geohashQueryBounds([lat,lng],radiusKm*1000);const snaps=await Promise.all(bounds.map(([start,end])=>db.collection("drivers").where("isDutyOn","==",true).where("isBusy","==",false).orderBy("geohash").startAt(start).endAt(end).get()));const seen=new Set<string>(),drivers:any[]=[];for(const snap of snaps)for(const doc of snap.docs){if(seen.has(doc.id))continue;const d=doc.data(),g=d.location as GeoPoint|undefined;if(!g)continue;const km=distanceBetween([g.latitude,g.longitude],[lat,lng]);if(km<=radiusKm){seen.add(doc.id);drivers.push({id:doc.id,lat:g.latitude,lng:g.longitude,bearing:d.bearing??0,distanceKm:km})}}return{drivers}});

export const syncDriverGeohash=onDocumentWritten({document:"drivers/{driverId}",region:REGION},async e=>{const after=e.data?.after;if(!after?.exists)return;const data=after.data()!,g=data.location as GeoPoint|undefined;if(!g)return;const hash=geohashForLocation([g.latitude,g.longitude]);if(data.geohash!==hash)await after.ref.update({geohash:hash})});

export const syncDriverQueueToken=onDocumentWritten({document:"drivers/{driverId}",region:REGION},async e=>{const after=e.data?.after;if(!after?.exists)return;const before=e.data?.before.data(),data=after.data()!;if(!data.standId||!data.fcmToken||before?.fcmToken===data.fcmToken)return;await queueRef(String(data.standId),e.params.driverId).set({fcmToken:data.fcmToken,updatedAt:Timestamp.now()},{merge:true})});
